version: '3'
services:
    association-db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: 'data'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "3306:3306"
        healthcheck:
            test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - association-data:/var/lib/mysql
    association-backend:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        ports:
            - "8080:8080"
            - "8000:8000"
        depends_on:
            association-db:
                condition: service_healthy
        links:
            - "association-db"
        environment:
            # JDBC
            - spring.datasource.url=jdbc:mysql://association-db:3306/data
            - spring.datasource.username=user
            - spring.datasource.password=password
            - spring.profiles.active=development
volumes:
    association-data: